---
#========= ADDUSER WORKAROUND =======
# The ansible 'user' module seems to use 'useradd' tool on linux.
# There is no way to make it use 'adduser' instead, and it causes problem.
# So this is an ugly workaround provided for information purposes.
# BTW, it works!
#
#- name: '[adduser.info.yml] Check if users do not already exist'
#  command: "id -u {{ item.username }}"
#  register: rpi_bootstrap_users_stat
#  with_items: "{{ rpi_bootstrap_users }}"
#  changed_when: false
#  failed_when: false
#  tags:
#  - rpi_bootstrap
#
#- name: '[adduser.info.yml] Flatten rpi_bootstrap_users_stat dictionary'
#  set_fact:
#    rpi_bootstrap_users_exist: "{{ rpi_bootstrap_users_exist|default({}) | combine( {item.item.username: item.rc} ) }}"
#  with_items: "{{ rpi_bootstrap_users_stat.results }}"
#  changed_when: false
#  tags:
#  - rpi_bootstrap
#
#- name: '[adduser.info.yml] Check if the group exists in the system'
#  shell: "getent group | cut -d: -f1"
#  register: rpi_bootstrap_system_groups
#  changed_when: false
#  tags:
#  - rpi_bootstrap
#
#- name: '[adduser.info.yml] Create specified users using "adduser" only when neither user nor its group do not exist'
#  shell: echo "{{ item.passwd }} | adduser "{{ item.username }}"
#  with_items: "{{ rpi_bootstrap_users }}"
#  become: yes
#  when:
#  - rpi_bootstrap_users_exist.{{ item.username }} != 0  # Produces Warning. I haven't find the way to get rid of '{'
#  - item.username not in rpi_bootstrap_system_groups.stdout_lines
#  tags:
#  - rpi_bootstrap
#
## There may be situation when the user we want to create already exists
## and is used for provisioning by current ansible process.
## then changing the password will break the role execution with "Authentication failed" error.
#- name: '[adduser.info.yml] Set passwords for users only when user is not currently authenticated for this provisioning'
#  user: name={{ item.username }} password={{ item.passwd }}
#  with_items: "{{ rpi_bootstrap_users }}"
#  become: yes
#  when: item.username != ansible_user_id
#  tags:
#  - rpi_bootstrap
#
#- name: '[adduser.info.yml] Add users to corresponding groups only if these groups exist'
#  user: name={{ item[0].username }} groups={{ item[1] }} append=yes
#  with_subelements:
#  - "{{ rpi_bootstrap_users }}"
#  - groups
#  when: item[1] in rpi_bootstrap_system_groups.stdout_lines
#  become: yes
#  tags:
#  - rpi_bootstrap
