---
#=========== LOCALE SETUP ============
- name: "[Debian] Set up {{ rpi_bootstrap_locale }} locale"
  locale_gen:
    name: "{{ rpi_bootstrap_locale }}"
    state: present
  become: yes
  tags: rpi_bootstrap
#=====================================

#========== DISTRO UPGRADE ===========
- name: "[Debian] Upgrading distro"
  apt: upgrade=dist autoclean=yes autoremove=yes
  become: yes
  register: rpi_bootstrap_upgrade_result
  until: rpi_bootstrap_upgrade_result is succeeded
  when: "'Debian' in ansible_os_family"
  tags: rpi_bootstrap
#=====================================

#========= UPDATING FIRMWARE: ========
- name: "[Debian] Installing latest rpi-update"
  apt: name=rpi-update state=latest force=yes
  become: yes
  register: rpi_bootstrap_upgrade_result
  until: rpi_bootstrap_upgrade_result is succeeded
  when:
  - rpi_bootstrap_firmware_update
  - "'Debian' in ansible_os_family"
  tags: rpi_bootstrap

- name: "[Debian] Updating firmware"
  command: rpi-update
  become: yes
  when:
  - rpi_bootstrap_firmware_update
  - "'Debian' in ansible_os_family"
  tags: rpi_bootstrap
#=====================================
