---
- name: '[dependencies] Install sudo package'
  package:
    name:
    - sudo
    - locales
    state: present
  become: yes
  register: rpi_bootstrap_dep_result
  until: rpi_bootstrap_dep_result is succeeded
  tags:
  - rpi_bootstrap
  - rpi_bootstrap_dependencies

- name: '[dependencies] Install pi-bluetooth package'
  package: name=pi-bluetooth state=present
  become: yes
  register: rpi_bootstrap_dep_result
  until: rpi_bootstrap_dep_result is succeeded
  when: rpi_bootstrap_bluetooth
  tags:
  - rpi_bootstrap
  - rpi_bootstrap_dependencies

- name: '[dependencies] Install ralink firmware package'
  package: name=firmware-ralink state=present
  become: yes
  register: rpi_bootstrap_dep_result
  until: rpi_bootstrap_dep_result is succeeded
  when: rpi_bootstrap_ralink_firmware
  tags:
  - rpi_bootstrap
  - rpi_bootstrap_dependencies
