---
#========= CONFIGURING PROMPT ========
# required because 'command: mv ' will return error
# if /etc/skel does not exist
- name: "[prompt] Check if /etc/skel exists"
  stat: path=/etc/skel
  register: skel_stat
  tags:
  - rpi_bootstrap
  - rpi_bootstrap_prompt

- name: "[prompt] Check if /etc/skel.dist exists (in case /etc/skel was already backed up)"
  stat: path=/etc/skel.dist
  register: skel_dist_stat
  tags:
  - rpi_bootstrap
  - rpi_bootstrap_prompt

- name: "[prompt] Backup distro /etc/skel"
  command: mv /etc/skel /etc/skel.dist
  become: yes
  when:
  - skel_stat.stat.exists
  - not skel_dist_stat.stat.exists
  tags:
  - rpi_bootstrap
  - rpi_bootstrap_prompt

- name: "[prompt] Copying /etc/skel contents"
  copy: src=etc_skel/ dest=/etc/skel
  become: yes
  tags:
  - rpi_bootstrap
  - rpi_bootstrap_prompt

- name: "[prompt] Copying .bashrc and .profile to home directory of current user"
  copy: src=etc_skel/ dest="{{ ansible_env.HOME }}/"
  tags:
  - rpi_bootstrap
  - rpi_bootstrap_prompt
#=====================================
