---
# CentOS does not have locales package available, but it has localectl command:
- name: '[RedHat] Set up en_US.UTF-8 locale'
  command: "localectl set-locale LANG={{ bootstrap_core_locale }}"
  become: yes
  tags:
  - bootstrap_core

- name: '[RedHat] Upgrading distro with yum'
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: bootstrap_core_upgrade_result
  until: bootstrap_core_upgrade_result is succeeded
  become: yes
  tags:
  - bootstrap_core

- name: '[RedHat] Create specified users'
  user: name={{ item.username }} password={{ item.passwd }} groups={{ item.groups }} append=yes
  with_items: "{{ bootstrap_core_users }}"
  become: yes
  tags:
  - bootstrap_core
