---
# CentOS does not have locales package available, but it has localectl command:
- name: "[RedHat] Set up {{ rpi_bootstrap_locale }} locale"
  command: "localectl set-locale LANG={{ rpi_bootstrap_locale }}"
  become: yes
  tags: rpi_bootstrap

- name: "[RedHat] Upgrading distro with yum"
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: rpi_bootstrap_upgrade_result
  until: rpi_bootstrap_upgrade_result is succeeded
  become: yes
  tags: rpi_bootstrap

- name: "[RedHat] Create specified users"
  user: name={{ item.username }} password={{ item.passwd }} groups={{ item.groups }} append=yes
  with_items: "{{ rpi_bootstrap_users }}"
  become: yes
  tags: rpi_bootstrap
